import{useCallback,useEffect,useRef,useState}from"react";import{FileText,Loader2,MessageCircle,Mic,Play,Send,Square,Trash2}from"lucide-react";import{useTranslation}from"react-i18next";import{toast}from"sonner";import{Button}from"@/components/ui/button";import{communicationsRepo,participantsRepo,proofsRepo}from"@/data";import{useAuth}from"@/features/identity";import{newClientMessageId}from"@/services/communication-rules";import type{Conversation,Document,Message}from"@/core/types/domain";

function AudioMessage({path}:{path:string}){const[url,setUrl]=useState("");useEffect(()=>{void communicationsRepo.getAudioUrl(path).then(setUrl);},[path]);return url?<audio controls className="w-full h-9" src={url}/>:<Loader2 className="size-4 animate-spin"/>;}
export function ExchangesSection({dossierId,ownerId}:{dossierId:string;ownerId:string}){
 const{t}=useTranslation();const{user}=useAuth();const[conversations,setConversations]=useState<Conversation[]>([]);const[selected,setSelected]=useState<string|null>(null);const[messages,setMessages]=useState<Message[]>([]);const[documents,setDocuments]=useState<Document[]>([]);const[text,setText]=useState("");const[loading,setLoading]=useState(true);const[more,setMore]=useState(false);const[recording,setRecording]=useState(false);const[audio,setAudio]=useState<Blob|null>(null);const[documentId,setDocumentId]=useState("");const recorder=useRef<MediaRecorder|null>(null);
 const loadConversations=useCallback(async()=>{const list=await communicationsRepo.getConversationsForDossier(dossierId);setConversations(list);setSelected(current=>current??list[0]?.id??null);},[dossierId]);
 useEffect(()=>{void(async()=>{setLoading(true);try{await loadConversations();setDocuments(await proofsRepo.getDocumentsForDossier(dossierId));}finally{setLoading(false);}})();},[dossierId,loadConversations]);
 const loadMessages=useCallback(async(before?:string)=>{if(!selected)return;const page=await communicationsRepo.getMessages(selected,before);setMessages(current=>before?[...page,...current]:page);setMore(page.length===30);},[selected]);
 useEffect(()=>{setMessages([]);void loadMessages();},[loadMessages]);
 const create=async()=>{if(!user)return;try{const participants=await participantsRepo.getParticipants(dossierId);const ids=[ownerId,...participants.map(p=>p.user_id).filter((id):id is string=>Boolean(id))].filter((id,i,a)=>a.indexOf(id)===i&&id!==user.id);const id=await communicationsRepo.createConversation({type:"dossier",dossierId},ids);await loadConversations();setSelected(id);}catch(e){toast.error(e instanceof Error?e.message:t("auth.error"));}};
 const sendText=async(value=text)=>{if(!selected||!value.trim())return;const id=newClientMessageId();try{await communicationsRepo.sendTextMessage(selected,value,id);setText("");await loadMessages();}catch(e){toast.error(e instanceof Error?e.message:t("auth.error"));}};
 const start=async()=>{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks:BlobPart[]=[];const r=new MediaRecorder(stream);r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{setAudio(new Blob(chunks,{type:r.mimeType||"audio/webm"}));stream.getTracks().forEach(track=>track.stop());};recorder.current=r;r.start();setRecording(true);};
 const stop=()=>{recorder.current?.stop();setRecording(false);};
 const sendAudio=async()=>{if(!selected||!audio)return;try{await communicationsRepo.sendAudioMessage(selected,audio,newClientMessageId());setAudio(null);await loadMessages();}catch(e){toast.error(e instanceof Error?e.message:t("auth.error"));}};
 const sendDocument=async()=>{if(!selected||!documentId)return;await communicationsRepo.sendDocumentMessage(selected,documentId,newClientMessageId());setDocumentId("");await loadMessages();};
 if(loading)return <section className="card-soft p-5 mb-4"><Loader2 className="size-5 animate-spin"/></section>;
 return <section className="card-soft p-5 mb-4 space-y-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-medium flex items-center gap-2"><MessageCircle className="size-4"/>{t("communications.title")}</h2><p className="text-caption">{t("communications.hint")}</p></div>{conversations.length===0&&<Button size="sm" onClick={()=>void create()}>{t("communications.start")}</Button>}</div>
 {conversations.length>0&&<><select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={selected??""} onChange={e=>setSelected(e.target.value)}>{conversations.map(c=><option key={c.id} value={c.id}>{t(`communications.contexts.${c.conversation_type}`)}</option>)}</select>
 <div className="max-h-80 overflow-y-auto space-y-2">{more&&<Button size="sm" variant="ghost" onClick={()=>void loadMessages(messages[0]?.created_at)}>{t("communications.older")}</Button>}{messages.map(m=><div key={m.id} className={`rounded-xl p-3 text-sm ${m.sender_user_id===user?.id?"bg-primary/10 ml-6":"bg-muted mr-6"}`}>{m.message_type==="audio"&&m.audio_path?<AudioMessage path={m.audio_path}/>:m.message_type==="document"?<span className="flex gap-2"><FileText className="size-4"/>{t("communications.document")}</span>:<p>{m.text_content}</p>}<p className="text-[10px] text-muted-foreground mt-1">{new Date(m.created_at).toLocaleString()}</p></div>)}</div>
 <div className="flex flex-wrap gap-2">{["yes","understood","sendDocument","needHelp"].map(key=><Button key={key} size="sm" variant="outline" onClick={()=>void sendText(t(`communications.quick.${key}`))}>{t(`communications.quick.${key}`)}</Button>)}</div>
 <div className="flex gap-2"><input className="flex-1 rounded-md border bg-background px-3 py-2 text-sm" value={text} onChange={e=>setText(e.target.value)} placeholder={t("communications.write")}/><Button size="icon" onClick={()=>void sendText()}><Send className="size-4"/></Button></div>
 <div className="flex gap-2 items-center">{!recording?<Button variant="outline" size="sm" onClick={()=>void start()}><Mic className="size-4"/>{t("communications.record")}</Button>:<Button variant="destructive" size="sm" onClick={stop}><Square className="size-4"/>{t("communications.stop")}</Button>}{audio&&<><audio controls src={URL.createObjectURL(audio)} className="h-9 max-w-40"/><Button size="sm" onClick={()=>void sendAudio()}><Play className="size-4"/>{t("communications.sendAudio")}</Button><Button size="icon" variant="ghost" onClick={()=>setAudio(null)}><Trash2 className="size-4"/></Button></>}</div>
 {documents.length>0&&<div className="flex gap-2"><select className="flex-1 rounded-md border bg-background px-3 py-2 text-sm" value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">{t("communications.chooseDocument")}</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><Button disabled={!documentId} onClick={()=>void sendDocument()}>{t("communications.attach")}</Button></div>}</>}
 </section>;
}
