import{useCallback,useEffect,useState}from"react";import{AlertTriangle,Loader2,Plus}from"lucide-react";import{useTranslation}from"react-i18next";import{toast}from"sonner";import{Button}from"@/components/ui/button";import{interventionsRepo,participantsRepo,proceduresRepo,proofsRepo,signalementsRepo}from"@/data";import{useAuth}from"@/features/identity";import{nextSignalementAction,SIGNALEMENT_TYPES,type SignalementType}from"@/services/signalement-flow";import type{Document,DossierIntervention,DossierStep,Signalement}from"@/core/types/domain";
export function SignalementsSection({dossierId,bienId}:{dossierId:string;bienId:string}){
 const{t}=useTranslation();const{user}=useAuth();const[items,setItems]=useState<Signalement[]>([]);const[steps,setSteps]=useState<DossierStep[]>([]);const[interventions,setInterventions]=useState<DossierIntervention[]>([]);const[documents,setDocuments]=useState<Document[]>([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[type,setType]=useState<SignalementType>("etape_mal_traitee");const[description,setDescription]=useState("");const[expected,setExpected]=useState("");const[stepId,setStepId]=useState("");const[interventionId,setInterventionId]=useState("");const[documentId,setDocumentId]=useState("");const[witnessId,setWitnessId]=useState("");const[role,setRole]=useState("declarant");
 const load=useCallback(async()=>{if(!user)return;setLoading(true);try{const[s,i,d,p,parts]=await Promise.all([signalementsRepo.getSignalementsForDossier(dossierId),interventionsRepo.getInterventionsForDossier(dossierId),proofsRepo.getDocumentsForDossier(dossierId),proceduresRepo.getDossierSteps(dossierId),participantsRepo.getParticipants(dossierId)]);setItems(s);setInterventions(i);setDocuments(d);setSteps(p);const mine=parts.find(x=>x.person.linked_profile_id===user.id||x.user_id===user.id);if(mine)setRole(mine.role);}finally{setLoading(false);}},[dossierId,user]);
 useEffect(()=>{void load();},[load]);
 const create=async()=>{if(description.trim().length<10)return;try{const sid=await signalementsRepo.createSignalement({bienId,dossierId,stepId:stepId||null,interventionId:interventionId||null,type,description,expectedResolution:expected||null,role});if(documentId)await signalementsRepo.attachDocument(sid,documentId);if(witnessId)await signalementsRepo.addWitness(sid,witnessId,null);setDescription("");setExpected("");setStepId("");setInterventionId("");setDocumentId("");setWitnessId("");setOpen(false);await load();toast.success(t("signalements.created"));}catch(e){toast.error(e instanceof Error?e.message:t("auth.error"));}};
 if(loading)return <section className="card-soft p-5 mb-4"><Loader2 className="size-5 animate-spin"/></section>;
 return <section className="card-soft p-5 mb-4 space-y-4"><div className="flex justify-between gap-3"><div><h2 className="font-medium flex items-center gap-2"><AlertTriangle className="size-4"/>{t("signalements.title")}</h2><p className="text-caption">{t("signalements.hint")}</p></div><Button size="sm" variant="outline" onClick={()=>setOpen(v=>!v)}><Plus className="size-4"/>{t("signalements.add")}</Button></div>
 {open&&<div className="rounded-xl border p-3 space-y-3"><label className="text-sm font-medium">{t("signalements.what")}</label><select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={type} onChange={e=>setType(e.target.value as SignalementType)}>{SIGNALEMENT_TYPES.map(v=><option key={v} value={v}>{t(`signalements.types.${v}`)}</option>)}</select><textarea className="w-full rounded-md border bg-background px-3 py-2 text-sm min-h-24" value={description} onChange={e=>setDescription(e.target.value)} placeholder={t("signalements.describe")}/>
 <select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={stepId} onChange={e=>setStepId(e.target.value)}><option value="">{t("signalements.noStep")}</option>{steps.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select>
 <select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={interventionId} onChange={e=>setInterventionId(e.target.value)}><option value="">{t("signalements.noIntervention")}</option>{interventions.map(i=><option key={i.id} value={i.id}>{t(`interventions.actions.${i.action_type}`)} · {new Date(i.performed_at).toLocaleDateString()}</option>)}</select>
 <textarea className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={expected} onChange={e=>setExpected(e.target.value)} placeholder={t("signalements.expected")}/><select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">{t("signalements.noDocument")}</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><Button disabled={description.trim().length<10} onClick={()=>void create()}>{t("signalements.save")}</Button></div>}
 <div className="space-y-3">{items.length===0?<p className="text-caption">{t("signalements.empty")}</p>:items.map(s=><article key={s.id} className="rounded-xl border p-3"><p className="text-sm font-medium">{t(`signalements.types.${s.signalement_type}`)}</p><p className="text-caption">{t(`signalements.statuses.${s.status}`)} · {new Date(s.created_at).toLocaleDateString()}</p><p className="text-sm mt-2 line-clamp-3">{s.description}</p><p className="text-caption mt-2">{t("signalements.next")}: {t(`signalements.actions.${nextSignalementAction(s.status as never)}`)}</p>{["brouillon","a_documenter","a_verifier"].includes(s.status)&&<Button size="sm" className="mt-2" onClick={async()=>{await signalementsRepo.updateSignalementStatus(s.id,"transmis");await load();}}>{t("signalements.submit")}</Button>}</article>)}</div></section>;
}
